export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_REQUEST_SUCCESS = "PRODUCT_REQUEST_SUCCESS";
export const PRODUCT_REQUEST_FAIL = "PRODUCT_REQUEST_FAIL";

export const PRODUCT_DETAIL_REQUEST = "RODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_REQUEST_SUCCESS = "RODUCT_DETAIL_REQUEST_SUCCESS";
export const PRODUCT_DETAIL_REQUEST_FAIL = "RODUCT_DETAIL_REQUEST_FAIL";
